server {
    listen       8081;
    listen  [::]:8081;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location = /admin {
        return 301 $scheme://$http_host/admin/;
    }

    location /admin/ {
        alias   /usr/share/nginx/html/;
        index  index.html index.htm;
        try_files $uri $uri/ /admin/index.html;
    }

    location = /admin {
        alias   /usr/share/nginx/html/index.html;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location /health {
        default_type application/json;
        return 200 '{"status":"ok","version":"${APP_VERSION}"}';
    }

    location /admin/api/makeline/order/fetch {
        proxy_pass http://makeline-service:3001/order/fetch;
        proxy_http_version 1.1;
    }

    location ~ ^/admin/api/makeline/order/(?<id>\w+) {
        proxy_pass http://makeline-service:3001/order/$id;
        proxy_http_version 1.1;
    }

    location /admin/api/makeline/order {
        proxy_pass http://makeline-service:3001/order;
        proxy_http_version 1.1;
    }

    location /admin/api/order {
        proxy_pass http://order-service:3000/;
        proxy_http_version 1.1;
    }

    location /admin/api/products/ {
        proxy_pass http://product-service:3002/;
        proxy_http_version 1.1;
    }

    location /admin/api/products {
        proxy_pass http://product-service:3002/;
        proxy_http_version 1.1;
    }

    location ~ ^/admin/api/product/(?<id>\w+) {
        proxy_pass http://product-service:3002/$id;
        proxy_http_version 1.1;
    }

    location /admin/api/product/ {
        proxy_pass http://product-service:3002/;
        proxy_http_version 1.1;
    }

    location /admin/api/product {
        proxy_pass http://product-service:3002/;
        proxy_http_version 1.1;
    }

    location /admin/api/ai/health {
        proxy_pass http://product-service:3002/ai/health;
        proxy_http_version 1.1;
    }

    location /admin/api/ai/generate/description {
        proxy_pass http://product-service:3002/ai/generate/description;
        proxy_http_version 1.1;
    }

    location /admin/api/ai/generate/image {
        proxy_pass http://product-service:3002/ai/generate/image;
        proxy_http_version 1.1;
    }
}